#include "Common.h"

std::array<std::string_view, 32> getPrettyFlagNamesFor(uint16_t minorVersion, vtfpp::VTF::Platform) {
	if (minorVersion <= 1) {
		return {
			"Point Sample",
			"Trilinear",
			"Clamp S",
			"Clamp T",
			"Anisotropic",
			"Hint DXT5",
			"Unused (1<<6)",
			"Normal",
			"No Mips",
			"No LOD",
			"Min Mip",
			"Procedural",
			"One-bit Alpha",
			"Multi-bit Alpha",
			"Envmap",
			"Rendertarget",
			"Depth Rendertarget",
			"No Debug Override",
			"Single Copy",
			"Unused (1<<19)",
			"Unused (1<<20)",
			"Unused (1<<21)",
			"Unused (1<<22)",
			"Unused (1<<23)",
			"Unused (1<<24)",
			"Unused (1<<25)",
			"Unused (1<<26)",
			"Unused (1<<27)",
			"Unused (1<<28)",
			"Unused (1<<29)",
			"Unused (1<<30)",
			"Unused (1<<31)",
		};
	}
	if (minorVersion <= 2) {
		return {
			"Point Sample",
			"Trilinear",
			"Clamp S",
			"Clamp T",
			"Anisotropic",
			"Hint DXT5",
			"Unused (1<<6)",
			"Normal",
			"No Mips",
			"No LOD",
			"Min Mip",
			"Procedural",
			"One-bit Alpha",
			"Multi-bit Alpha",
			"Envmap",
			"Rendertarget",
			"Depth Rendertarget",
			"No Debug Override",
			"Single Copy",
			"Unused (1<<19)",
			"Unused (1<<20)",
			"Unused (1<<21)",
			"Unused (1<<22)",
			"No Depth Buffer",
			"Unused (1<<24)",
			"Clamp U",
			"Unused (1<<26)",
			"Unused (1<<27)",
			"Unused (1<<28)",
			"Unused (1<<29)",
			"Unused (1<<30)",
			"Unused (1<<31)",
		};
	}
	if (minorVersion <= 3) {
		return {
			"Point Sample",
			"Trilinear",
			"Clamp S",
			"Clamp T",
			"Anisotropic",
			"Hint DXT5",
			"Unused (1<<6)",
			"Normal",
			"No Mips",
			"No LOD",
			"Load All Mips",
			"Procedural",
			"One-bit Alpha",
			"Multi-bit Alpha",
			"Envmap",
			"Rendertarget",
			"Depth Rendertarget",
			"No Debug Override",
			"Single Copy",
			"Unused (1<<19)",
			"Unused (1<<20)",
			"Unused (1<<21)",
			"Unused (1<<22)",
			"No Depth Buffer",
			"Unused (1<<24)",
			"Clamp U",
			"Vertex Texture",
			"SSBump",
			"Unused (1<<28)",
			"Border",
			"Unused (1<<30)",
			"Unused (1<<31)",
		};
	}
	if (minorVersion <= 4) {
		return {
			"Point Sample",
			"Trilinear",
			"Clamp S",
			"Clamp T",
			"Anisotropic",
			"Hint DXT5",
			"SRGB",
			"Normal",
			"No Mips",
			"No LOD",
			"Load All Mips",
			"Procedural",
			"One-bit Alpha",
			"Multi-bit Alpha",
			"Envmap",
			"Rendertarget",
			"Depth Rendertarget",
			"No Debug Override",
			"Single Copy",
			"(TF2) Staging Memory",
			"(TF2) Immediate Cleanup",
			"(TF2) Ignore mat_picmip",
			"Unused (1<<22)",
			"No Depth Buffer",
			"Unused (1<<24)",
			"Clamp U",
			"Vertex Texture",
			"SSBump",
			"Unused (1<<28)",
			"Border",
			"(TF2) Streamable (Coarse)",
			"(TF2) Streamable (Fine)",
		};
	}
	return {
		"Point Sample",
		"Trilinear",
		"Clamp S",
		"Clamp T",
		"Anisotropic",
		"Hint DXT5",
		"PWL Corrected",
		"Normal",
		"No Mips",
		"No LOD",
		"Load All Mips",
		"Procedural",
		"One-bit Alpha",
		"Multi-bit Alpha",
		"Envmap",
		"Rendertarget",
		"Depth Rendertarget",
		"No Debug Override",
		"Single Copy",
		"SRGB",
		"Default Pool",
		"(CS:GO) Combined",
		"(CS:GO) Async Download",
		"No Depth Buffer",
		"(CS:GO) Skip Initial Download",
		"Clamp U",
		"Vertex Texture",
		"SSBump",
		"Load Most Mips",
		"Border",
		"(CS:GO) YCoCg",
		"(CS:GO) Async Skip Initial Low Res",
	};
}
