#include "EnumMappings.h"

namespace not_magic_enum::detail {

const std::vector<vtfpp::HOT::Rect::Flags> HOT_RECT_FLAGS_E{
	vtfpp::HOT::Rect::FLAG_ALLOW_RANDOM_ROTATION,
	vtfpp::HOT::Rect::FLAG_ALLOW_RANDOM_REFLECTION,
	vtfpp::HOT::Rect::FLAG_IS_ALTERNATE,
};
const std::vector<std::string_view> HOT_RECT_FLAGS_S{
	"ALLOW_RANDOM_ROTATION",
	"ALLOW_RANDOM_REFLECTION",
	"IS_ALTERNATE",
};

const std::vector<vtfpp::ImageFormat> IMAGE_FORMAT_E{
	vtfpp::VTF::FORMAT_UNCHANGED,
	vtfpp::VTF::FORMAT_DEFAULT,
	vtfpp::ImageFormat::RGBA8888,
	vtfpp::ImageFormat::ABGR8888,
	vtfpp::ImageFormat::RGB888,
	vtfpp::ImageFormat::BGR888,
	vtfpp::ImageFormat::RGB565,
	vtfpp::ImageFormat::I8,
	vtfpp::ImageFormat::IA88,
	vtfpp::ImageFormat::P8,
	vtfpp::ImageFormat::A8,
	vtfpp::ImageFormat::RGB888_BLUESCREEN,
	vtfpp::ImageFormat::BGR888_BLUESCREEN,
	vtfpp::ImageFormat::ARGB8888,
	vtfpp::ImageFormat::BGRA8888,
	vtfpp::ImageFormat::DXT1,
	vtfpp::ImageFormat::DXT3,
	vtfpp::ImageFormat::DXT5,
	vtfpp::ImageFormat::BGRX8888,
	vtfpp::ImageFormat::BGR565,
	vtfpp::ImageFormat::BGRX5551,
	vtfpp::ImageFormat::BGRA4444,
	vtfpp::ImageFormat::DXT1_ONE_BIT_ALPHA,
	vtfpp::ImageFormat::BGRA5551,
	vtfpp::ImageFormat::UV88,
	vtfpp::ImageFormat::UVWQ8888,
	vtfpp::ImageFormat::RGBA16161616F,
	vtfpp::ImageFormat::RGBA16161616,
	vtfpp::ImageFormat::UVLX8888,
	vtfpp::ImageFormat::R32F,
	vtfpp::ImageFormat::RGB323232F,
	vtfpp::ImageFormat::RGBA32323232F,
	vtfpp::ImageFormat::RG1616F,
	vtfpp::ImageFormat::RG3232F,
	vtfpp::ImageFormat::RGBX8888,
	vtfpp::ImageFormat::EMPTY,
	vtfpp::ImageFormat::ATI2N,
	vtfpp::ImageFormat::ATI1N,
	vtfpp::ImageFormat::RGBA1010102,
	vtfpp::ImageFormat::BGRA1010102,
	vtfpp::ImageFormat::R16F,
	vtfpp::ImageFormat::CONSOLE_BGRX8888_LINEAR,
	vtfpp::ImageFormat::CONSOLE_RGBA8888_LINEAR,
	vtfpp::ImageFormat::CONSOLE_ABGR8888_LINEAR,
	vtfpp::ImageFormat::CONSOLE_ARGB8888_LINEAR,
	vtfpp::ImageFormat::CONSOLE_BGRA8888_LINEAR,
	vtfpp::ImageFormat::CONSOLE_RGB888_LINEAR,
	vtfpp::ImageFormat::CONSOLE_BGR888_LINEAR,
	vtfpp::ImageFormat::CONSOLE_BGRX5551_LINEAR,
	vtfpp::ImageFormat::CONSOLE_I8_LINEAR,
	vtfpp::ImageFormat::CONSOLE_RGBA16161616_LINEAR,
	vtfpp::ImageFormat::CONSOLE_BGRX8888_LE,
	vtfpp::ImageFormat::CONSOLE_BGRA8888_LE,
	vtfpp::ImageFormat::R8,
	vtfpp::ImageFormat::BC7,
	vtfpp::ImageFormat::BC6H,
};
const std::vector<std::string_view> IMAGE_FORMAT_S{
	"UNCHANGED",
	"DEFAULT",
	"RGBA8888",
	"ABGR8888",
	"RGB888",
	"BGR888",
	"RGB565",
	"I8",
	"IA88",
	"P8",
	"A8",
	"RGB888_BLUESCREEN",
	"BGR888_BLUESCREEN",
	"ARGB8888",
	"BGRA8888",
	"DXT1",
	"DXT3",
	"DXT5",
	"BGRX8888",
	"BGR565",
	"BGRX5551",
	"BGRA4444",
	"DXT1_ONE_BIT_ALPHA",
	"BGRA5551",
	"UV88",
	"UVWQ8888",
	"RGBA16161616F",
	"RGBA16161616",
	"UVLX8888",
	"R32F",
	"RGB323232F",
	"RGBA32323232F",
	"RG1616F",
	"RG3232F",
	"RGBX8888",
	"EMPTY",
	"ATI2N",
	"ATI1N",
	"RGBA1010102",
	"BGRA1010102",
	"R16F",
	"CONSOLE_BGRX8888_LINEAR",
	"CONSOLE_RGBA8888_LINEAR",
	"CONSOLE_ABGR8888_LINEAR",
	"CONSOLE_ARGB8888_LINEAR",
	"CONSOLE_BGRA8888_LINEAR",
	"CONSOLE_RGB888_LINEAR",
	"CONSOLE_BGR888_LINEAR",
	"CONSOLE_BGRX5551_LINEAR",
	"CONSOLE_I8_LINEAR",
	"CONSOLE_RGBA16161616_LINEAR",
	"CONSOLE_BGRX8888_LE",
	"CONSOLE_BGRA8888_LE",
	"R8",
	"BC7",
	"BC6H",
};

const std::vector<vtfpp::ImageConversion::FileFormat> IMAGE_CONVERSION_FILE_FORMAT_E{
	vtfpp::ImageConversion::FileFormat::DEFAULT,
	vtfpp::ImageConversion::FileFormat::PNG,
	vtfpp::ImageConversion::FileFormat::JPG,
	vtfpp::ImageConversion::FileFormat::JPG,
	vtfpp::ImageConversion::FileFormat::BMP,
	vtfpp::ImageConversion::FileFormat::TGA,
	vtfpp::ImageConversion::FileFormat::WEBP,
	vtfpp::ImageConversion::FileFormat::QOI,
	vtfpp::ImageConversion::FileFormat::HDR,
	vtfpp::ImageConversion::FileFormat::EXR,
};
const std::vector<std::string_view> IMAGE_CONVERSION_FILE_FORMAT_S{
	"DEFAULT",
	"PNG",
	"JPG",
	"JPEG",
	"BMP",
	"TGA",
	"WEBP",
	"QOI",
	"HDR",
	"EXR",
};

const std::vector<vtfpp::ImageConversion::ResizeFilter> IMAGE_CONVERSION_RESIZE_FILTER_E{
	vtfpp::ImageConversion::ResizeFilter::DEFAULT,
	vtfpp::ImageConversion::ResizeFilter::BOX,
	vtfpp::ImageConversion::ResizeFilter::BILINEAR,
	vtfpp::ImageConversion::ResizeFilter::CUBIC_BSPLINE,
	vtfpp::ImageConversion::ResizeFilter::CATMULL_ROM,
	vtfpp::ImageConversion::ResizeFilter::MITCHELL,
	vtfpp::ImageConversion::ResizeFilter::POINT_SAMPLE,
	vtfpp::ImageConversion::ResizeFilter::KAISER,
	vtfpp::ImageConversion::ResizeFilter::NICE,
};
const std::vector<std::string_view> IMAGE_CONVERSION_RESIZE_FILTER_S{
	"DEFAULT",
	"BOX",
	"BILINEAR",
	"CUBIC_BSPLINE",
	"CATMULL_ROM",
	"MITCHELL",
	"POINT_SAMPLE",
	"KAISER",
	"NICE",
};

const std::vector<vtfpp::ImageConversion::ResizeMethod> IMAGE_CONVERSION_RESIZE_METHOD_E{
	vtfpp::ImageConversion::ResizeMethod::NONE,
	vtfpp::ImageConversion::ResizeMethod::POWER_OF_TWO_BIGGER,
	vtfpp::ImageConversion::ResizeMethod::POWER_OF_TWO_SMALLER,
	vtfpp::ImageConversion::ResizeMethod::POWER_OF_TWO_NEAREST,
};
const std::vector<std::string_view> IMAGE_CONVERSION_RESIZE_METHOD_S{
	"NONE",
	"BIGGER",
	"SMALLER",
	"NEAREST",
};

const std::vector<vtfpp::CompressionMethod> COMPRESSION_METHOD_E{
	vtfpp::CompressionMethod::DEFLATE,
	vtfpp::CompressionMethod::ZSTD,
	vtfpp::CompressionMethod::CONSOLE_LZMA,
};
const std::vector<std::string_view> COMPRESSION_METHOD_S{
	"DEFLATE",
	"ZSTD",
	"CONSOLE_LZMA",
};

const std::vector<vtfpp::Resource::Type> RESOURCE_TYPE_E{
	vtfpp::Resource::TYPE_THUMBNAIL_DATA,
	vtfpp::Resource::TYPE_IMAGE_DATA,
	vtfpp::Resource::TYPE_PARTICLE_SHEET_DATA,
	vtfpp::Resource::TYPE_CRC,
	vtfpp::Resource::TYPE_LOD_CONTROL_INFO,
	vtfpp::Resource::TYPE_EXTENDED_FLAGS,
	vtfpp::Resource::TYPE_KEYVALUES_DATA,
	vtfpp::Resource::TYPE_HOTSPOT_DATA,
	vtfpp::Resource::TYPE_AUX_COMPRESSION,
};
const std::vector<std::string_view> RESOURCE_TYPE_S{
	"THUMBNAIL",
	"IMAGE",
	"PARTICLE_SHEET",
	"CRC",
	"LOD_CONTROL_INFO",
	"EXTENDED_FLAGS",
	"KEYVALUES_DATA",
	"HOTSPOT_DATA",
	"AUX_COMPRESSION",
};

const std::vector<vtfpp::VTFFlags> VTF_FLAGS_E{
	// FlagsV0
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_POINT_SAMPLE),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_TRILINEAR),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_CLAMP_S),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_CLAMP_T),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_ANISOTROPIC),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_HINT_DXT5),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_NORMAL),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_NO_MIP),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_NO_LOD),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_PROCEDURAL),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_ONE_BIT_ALPHA),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_MULTI_BIT_ALPHA),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_ENVMAP),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_RENDERTARGET),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_DEPTH_RENDERTARGET),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_NO_DEBUG_OVERRIDE),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_SINGLE_COPY),
	// FlagsV2
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V2_NO_DEPTH_BUFFER),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V2_CLAMP_U),
	// FlagsV3
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V3_LOAD_ALL_MIPS),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V3_VERTEX_TEXTURE),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V3_SSBUMP),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V3_BORDER),
	// FlagsV4
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V4_SRGB),
	// FlagsV4_TF2
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V4_TF2_STAGING_MEMORY),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V4_TF2_IMMEDIATE_CLEANUP),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V4_TF2_IGNORE_PICMIP),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V4_TF2_STREAMABLE_COARSE),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V4_TF2_STREAMABLE_FINE),
	// FlagsV5
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_PWL_CORRECTED),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_SRGB),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_DEFAULT_POOL),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_LOAD_MOST_MIPS),
	// FlagsV5_CSGO
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_CSGO_COMBINED),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_CSGO_ASYNC_DOWNLOAD),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_CSGO_SKIP_INITIAL_DOWNLOAD),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_CSGO_YCOCG),
	static_cast<vtfpp::VTFFlags>(vtfpp::VTF::FLAG_V5_CSGO_ASYNC_SKIP_INITIAL_LOW_RES),
};
const std::vector<std::string_view> VTF_FLAGS_S{
	// FlagsV0
	"POINT_SAMPLE",
	"TRILINEAR",
	"CLAMP_S",
	"CLAMP_T",
	"ANISOTROPIC",
	"HINT_DXT5",
	"NORMAL",
	"NO_MIP",
	"NO_LOD",
	"PROCEDURAL",
	"ONE_BIT_ALPHA",
	"MULTI_BIT_ALPHA",
	"ENVMAP",
	"RENDERTARGET",
	"DEPTH_RENDERTARGET",
	"NO_DEBUG_OVERRIDE",
	"SINGLE_COPY",
	// FlagsV2
	"V2_NO_DEPTH_BUFFER",
	"V2_CLAMP_U",
	// FlagsV3
	"V3_LOAD_ALL_MIPS",
	"V3_VERTEX_TEXTURE",
	"V3_SSBUMP",
	"V3_BORDER",
	// FlagsV4
	"V4_SRGB",
	// FlagsV4_TF2
	"V4_TF2_STAGING_MEMORY",
	"V4_TF2_IMMEDIATE_CLEANUP",
	"V4_TF2_IGNORE_PICMIP",
	"V4_TF2_STREAMABLE_COARSE",
	"V4_TF2_STREAMABLE_FINE",
	// FlagsV5
	"V5_PWL_CORRECTED",
	"V5_SRGB",
	"V5_DEFAULT_POOL",
	"V5_LOAD_MOST_MIPS",
	// FlagsV5_CSGO
	"V5_CSGO_COMBINED",
	"V5_CSGO_ASYNC_DOWNLOAD",
	"V5_CSGO_SKIP_INITIAL_DOWNLOAD",
	"V5_CSGO_YCOCG",
	"V5_CSGO_ASYNC_SKIP_INITIAL_LOW_RES",
};

const std::vector<vtfpp::VTF::Platform> VTF_PLATFORM_E{
	vtfpp::VTF::PLATFORM_PC,
	vtfpp::VTF::PLATFORM_PS3_PORTAL2,
	vtfpp::VTF::PLATFORM_PS3_ORANGEBOX,
	vtfpp::VTF::PLATFORM_X360,
};
const std::vector<std::string_view> VTF_PLATFORM_S{
	"PC",
	"PS3_PORTAL2",
	"PS3_ORANGEBOX",
	"X360",
};

} // namespace not_magic_enum::detail
